name: smart_catering_service
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  ####################
  # Utils #
  ####################
  connectivity_plus: ^4.0.0
  equatable: ^2.0.5
  intl: ^0.18.1
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.10
  uuid: ^3.0.7

  ####################
  # State management #
  ####################
  provider: ^6.0.5

  ############
  # Firebase #
  ############
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.2.1
#  firebase_messaging: ^14.6.1
  google_sign_in: ^6.1.4
  carousel_slider: ^4.2.1

  #######
  # UI #
  #######
  cached_network_image: ^3.2.3
  circular_countdown_timer: ^0.2.3
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.4
  material_design_icons_flutter: ^6.0.7096
  flutter_spinkit: ^5.2.0
  loading_animation_widget: ^1.2.0+4
  shimmer: ^2.0.0
  fluttertoast: ^8.2.1
  smooth_page_indicator: ^1.1.0
  timer_count_down: ^2.2.2
  scrollable_positioned_list: ^0.3.8
  readmore: ^2.2.0
  overlay_support: ^2.1.0

  ###################
  # File Operations #
  ###################
  file_picker: ^5.3.0
  image_cropper: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/